apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
  labels:
    app: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics
  template:
    metadata:
      labels:
        app: metrics
    spec:
      containers:
        - name: metrics-container
          image: ghcr.io/arenabrab/practice@sha256:abc123... # {"$imagepolicy": "flux-system:metrics-image-policy"}

          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: "ps_user"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "SecurePassword"
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://postgres:5432/postgres
            - name: SPRING_R2DBC_USERNAME
              value: "ps_user"
            - name: SPRING_R2DBC_PASSWORD
              value: "SecurePassword"
#            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
#              value: org.hibernate.dialect.PostgreSQLDialect
#            - name: SPRING_PROFILES_ACTIVE
#              value: "prod"
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 1
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 1
            periodSeconds: 1