services:
#  zipkin:
#    image: 'openzipkin/zipkin:latest'
#    ports:
#      - '9411'

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432'
    volumes:
      - ./k8s/postgres/init:/docker-entrypoint-initdb.d

#  metrics:
#    image: docker.io/library/metrics:0.0.1-SNAPSHOT
#    ports:
#      - '8080'