spring:
  application:
    name: metrics
  datasource:
    url: jdbc:pg://localhost:5432
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  r2dbc:
    url: r2dbc:pg://localhost:5432
    password: password