spring:
  application:
    name: metrics
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    password: password