---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: metrics
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: practice
  policy:
    semver:
      range: 1.x
