---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: metrics
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: metrics
  policy:
    semver:
      range: 'metrics-0.0.1-SNAPSHOT'
