---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: metrics
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: practice
  filterTags:
    pattern: '^metrics-(\d+\.\d+\.\d+)(-SNAPSHOT)?$'
    extract: '$1'
  policy:
    semver:
      range: 0.x

