apiVersion: v1
kind: ConfigMap
metadata:
  name: init-script
  namespace: default
data:
  init-postgres: "CREATE TABLE metric (\r\n    id SERIAL PRIMARY KEY,\r\n    type VARCHAR(255) NOT NULL,\r\n    payload JSONB NOT NULL,\r\n    created_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),\r\n    last_modified_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),\r\n    version INTEGER NOT NULL DEFAULT 0\r\n);"
