apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-secret
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: init-script
      volumes:
        - name: init-script
          configMap:
            name: init-script
            items:
              - key: init-postgres
                path: init-postgres.sql

#          volumeMounts:
#            - mountPath: /var/lib/postgresql/data
#              name: postgresdata
#      volumes:
#        - name: postgresdata
#          persistentVolumeClaim:
#            claimName: postgres-volume-claim