name: workflow.yml
on:
  push:
    paths:
      - 'metrics/**'

jobs:
  run-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./metrics/.github/actions/local.yml