name: workflow.yml
on:
  push:
    paths:
      - 'metrics/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: chmod gradle
        run: chmod +x metrics/gradlew

      - name: bootBuildImage
        run: ./metrics/gradlew bBI

      - name: test
        run: ./metrics/gradlew check